version: '3.9'

services:
  price-scraper:
    image: murilodv/price-scraper:latest
    container_name: price-scraper
    ports:
      - "3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
    command: npm start
    networks:
      - webnet

networks:
  webnet:
    external: true